"""sessoes_usuario, tentativas_login, novos campos em usuarios

Revision ID: 6c6372519927
Revises: f19fae8abd7f
Create Date: 2026-07-15 13:51:09.440432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6372519927'
down_revision: Union[str, Sequence[str], None] = 'f19fae8abd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativas_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('data_tentativa', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tentativas_login_email'), 'tentativas_login', ['email'], unique=False)
    op.create_index(op.f('ix_tentativas_login_id'), 'tentativas_login', ['id'], unique=False)
    op.create_table('sessoes_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revogada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_usuario_id'), 'sessoes_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_sessoes_usuario_token'), 'sessoes_usuario', ['token'], unique=True)
    op.create_index(op.f('ix_sessoes_usuario_usuario_id'), 'sessoes_usuario', ['usuario_id'], unique=False)
    op.add_column('usuarios', sa.Column('numero_eng', sa.String(), nullable=True))
    # server_default='0' (ajustado à mão -- autogenerate não propõe default nenhum): sem
    # isso, ADD COLUMN NOT NULL falharia em cima de linhas já existentes num banco com dados
    # (ex.: bitin_backend.db real, que já tem usuários cadastrados). "0"/False é o valor
    # seguro pra quem já existe -- ninguém verificou e-mail retroativamente.
    op.add_column(
        'usuarios',
        sa.Column('email_verificado', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ultimo_acesso')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'email_verificado')
    op.drop_column('usuarios', 'numero_eng')
    op.drop_index(op.f('ix_sessoes_usuario_usuario_id'), table_name='sessoes_usuario')
    op.drop_index(op.f('ix_sessoes_usuario_token'), table_name='sessoes_usuario')
    op.drop_index(op.f('ix_sessoes_usuario_id'), table_name='sessoes_usuario')
    op.drop_table('sessoes_usuario')
    op.drop_index(op.f('ix_tentativas_login_id'), table_name='tentativas_login')
    op.drop_index(op.f('ix_tentativas_login_email'), table_name='tentativas_login')
    op.drop_table('tentativas_login')
    # ### end Alembic commands ###
